on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'poetry'

      - run: poetry install

      - name: Lint
        run: poetry run flake8

      - name: Unittest
        run: poetry run pytest --cov-report=xml --cov=./

      - uses: codecov/codecov-action@v3
