on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3

      - run: poetry install

      - name: Lint
        run: flake8

      - name: Unittest
        run: pytest --cov-report=xml --cov=./

      - uses: codecov/codecov-action@v3
